// 
// Decompiled by Procyon v0.5.30
// 

package android.support.graphics.drawable;

class AndroidResources
{
    public static final int FAST_OUT_LINEAR_IN = 17563663;
    public static final int FAST_OUT_SLOW_IN = 17563661;
    public static final int LINEAR_OUT_SLOW_IN = 17563662;
    static final int[] STYLEABLE_ANIMATED_VECTOR_DRAWABLE;
    static final int STYLEABLE_ANIMATED_VECTOR_DRAWABLE_DRAWABLE = 0;
    static final int[] STYLEABLE_ANIMATED_VECTOR_DRAWABLE_TARGET;
    static final int STYLEABLE_ANIMATED_VECTOR_DRAWABLE_TARGET_ANIMATION = 1;
    static final int STYLEABLE_ANIMATED_VECTOR_DRAWABLE_TARGET_NAME = 0;
    public static final int[] STYLEABLE_ANIMATOR;
    public static final int STYLEABLE_ANIMATOR_DURATION = 1;
    public static final int STYLEABLE_ANIMATOR_INTERPOLATOR = 0;
    public static final int STYLEABLE_ANIMATOR_REMOVE_BEFORE_M_RELEASE = 8;
    public static final int STYLEABLE_ANIMATOR_REPEAT_COUNT = 3;
    public static final int STYLEABLE_ANIMATOR_REPEAT_MODE = 4;
    public static final int[] STYLEABLE_ANIMATOR_SET;
    public static final int STYLEABLE_ANIMATOR_SET_ORDERING = 0;
    public static final int STYLEABLE_ANIMATOR_START_OFFSET = 2;
    public static final int STYLEABLE_ANIMATOR_VALUE_FROM = 5;
    public static final int STYLEABLE_ANIMATOR_VALUE_TO = 6;
    public static final int STYLEABLE_ANIMATOR_VALUE_TYPE = 7;
    public static final int[] STYLEABLE_KEYFRAME;
    public static final int STYLEABLE_KEYFRAME_FRACTION = 3;
    public static final int STYLEABLE_KEYFRAME_INTERPOLATOR = 1;
    public static final int STYLEABLE_KEYFRAME_VALUE = 0;
    public static final int STYLEABLE_KEYFRAME_VALUE_TYPE = 2;
    public static final int[] STYLEABLE_PATH_INTERPOLATOR;
    public static final int STYLEABLE_PATH_INTERPOLATOR_CONTROL_X_1 = 0;
    public static final int STYLEABLE_PATH_INTERPOLATOR_CONTROL_X_2 = 2;
    public static final int STYLEABLE_PATH_INTERPOLATOR_CONTROL_Y_1 = 1;
    public static final int STYLEABLE_PATH_INTERPOLATOR_CONTROL_Y_2 = 3;
    public static final int STYLEABLE_PATH_INTERPOLATOR_PATH_DATA = 4;
    public static final int[] STYLEABLE_PROPERTY_ANIMATOR;
    public static final int STYLEABLE_PROPERTY_ANIMATOR_PATH_DATA = 1;
    public static final int STYLEABLE_PROPERTY_ANIMATOR_PROPERTY_NAME = 0;
    public static final int STYLEABLE_PROPERTY_ANIMATOR_PROPERTY_X_NAME = 2;
    public static final int STYLEABLE_PROPERTY_ANIMATOR_PROPERTY_Y_NAME = 3;
    public static final int[] STYLEABLE_PROPERTY_VALUES_HOLDER;
    public static final int STYLEABLE_PROPERTY_VALUES_HOLDER_PROPERTY_NAME = 3;
    public static final int STYLEABLE_PROPERTY_VALUES_HOLDER_VALUE_FROM = 0;
    public static final int STYLEABLE_PROPERTY_VALUES_HOLDER_VALUE_TO = 1;
    public static final int STYLEABLE_PROPERTY_VALUES_HOLDER_VALUE_TYPE = 2;
    static final int STYLEABLE_VECTOR_DRAWABLE_ALPHA = 4;
    static final int STYLEABLE_VECTOR_DRAWABLE_AUTO_MIRRORED = 5;
    static final int[] STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH;
    static final int STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH_NAME = 0;
    static final int STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH_PATH_DATA = 1;
    static final int[] STYLEABLE_VECTOR_DRAWABLE_GROUP;
    static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_NAME = 0;
    static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_PIVOT_X = 1;
    static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_PIVOT_Y = 2;
    static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_ROTATION = 5;
    static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_SCALE_X = 3;
    static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_SCALE_Y = 4;
    static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_TRANSLATE_X = 6;
    static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_TRANSLATE_Y = 7;
    static final int STYLEABLE_VECTOR_DRAWABLE_HEIGHT = 2;
    static final int STYLEABLE_VECTOR_DRAWABLE_NAME = 0;
    static final int[] STYLEABLE_VECTOR_DRAWABLE_PATH;
    static final int STYLEABLE_VECTOR_DRAWABLE_PATH_FILL_ALPHA = 12;
    static final int STYLEABLE_VECTOR_DRAWABLE_PATH_FILL_COLOR = 1;
    static final int STYLEABLE_VECTOR_DRAWABLE_PATH_NAME = 0;
    static final int STYLEABLE_VECTOR_DRAWABLE_PATH_PATH_DATA = 2;
    static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_ALPHA = 11;
    static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_COLOR = 3;
    static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_LINE_CAP = 8;
    static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_LINE_JOIN = 9;
    static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_MITER_LIMIT = 10;
    static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_WIDTH = 4;
    static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_END = 6;
    static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_FILLTYPE = 13;
    static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_OFFSET = 7;
    static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_START = 5;
    static final int STYLEABLE_VECTOR_DRAWABLE_TINT = 1;
    static final int STYLEABLE_VECTOR_DRAWABLE_TINT_MODE = 6;
    static final int[] STYLEABLE_VECTOR_DRAWABLE_TYPE_ARRAY;
    static final int STYLEABLE_VECTOR_DRAWABLE_VIEWPORT_HEIGHT = 8;
    static final int STYLEABLE_VECTOR_DRAWABLE_VIEWPORT_WIDTH = 7;
    static final int STYLEABLE_VECTOR_DRAWABLE_WIDTH = 3;
    
    static {
        final int n = 9;
        final int[] array;
        final int[] styleable_VECTOR_DRAWABLE_TYPE_ARRAY = array = new int[n];
        array[0] = 16842755;
        array[1] = 16843041;
        array[2] = 16843093;
        array[3] = 16843097;
        array[4] = 16843551;
        array[5] = 16843754;
        array[6] = 16843771;
        array[7] = 16843778;
        array[8] = 16843779;
        STYLEABLE_VECTOR_DRAWABLE_TYPE_ARRAY = styleable_VECTOR_DRAWABLE_TYPE_ARRAY;
        final int[] array2;
        final int[] styleable_VECTOR_DRAWABLE_GROUP = array2 = new int[8];
        array2[0] = 16842755;
        array2[1] = 16843189;
        array2[2] = 16843190;
        array2[3] = 16843556;
        array2[4] = 16843557;
        array2[5] = 16843558;
        array2[6] = 16843866;
        array2[7] = 16843867;
        STYLEABLE_VECTOR_DRAWABLE_GROUP = styleable_VECTOR_DRAWABLE_GROUP;
        final int[] array3;
        final int[] styleable_VECTOR_DRAWABLE_PATH = array3 = new int[14];
        array3[0] = 16842755;
        array3[1] = 16843780;
        array3[2] = 16843781;
        array3[3] = 16843782;
        array3[4] = 16843783;
        array3[5] = 16843784;
        array3[6] = 16843785;
        array3[7] = 16843786;
        array3[8] = 16843787;
        array3[9] = 16843788;
        array3[10] = 16843789;
        array3[11] = 16843979;
        array3[12] = 16843980;
        array3[13] = 16844062;
        STYLEABLE_VECTOR_DRAWABLE_PATH = styleable_VECTOR_DRAWABLE_PATH;
        final int n2 = 2;
        final int[] array4;
        final int[] styleable_VECTOR_DRAWABLE_CLIP_PATH = array4 = new int[n2];
        array4[0] = 16842755;
        array4[1] = 16843781;
        STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH = styleable_VECTOR_DRAWABLE_CLIP_PATH;
        final int n3 = 1;
        final int[] styleable_ANIMATED_VECTOR_DRAWABLE = new int[n3];
        styleable_ANIMATED_VECTOR_DRAWABLE[0] = 16843161;
        STYLEABLE_ANIMATED_VECTOR_DRAWABLE = styleable_ANIMATED_VECTOR_DRAWABLE;
        final int[] array5;
        final int[] styleable_ANIMATED_VECTOR_DRAWABLE_TARGET = array5 = new int[n2];
        array5[0] = 16842755;
        array5[1] = 16843213;
        STYLEABLE_ANIMATED_VECTOR_DRAWABLE_TARGET = styleable_ANIMATED_VECTOR_DRAWABLE_TARGET;
        final int[] array6;
        final int[] styleable_ANIMATOR = array6 = new int[n];
        array6[0] = 16843073;
        array6[1] = 16843160;
        array6[2] = 16843198;
        array6[3] = 16843199;
        array6[4] = 16843200;
        array6[5] = 16843486;
        array6[6] = 16843487;
        array6[7] = 16843488;
        array6[8] = 17891484;
        STYLEABLE_ANIMATOR = styleable_ANIMATOR;
        final int[] styleable_ANIMATOR_SET = new int[n3];
        styleable_ANIMATOR_SET[0] = 16843490;
        STYLEABLE_ANIMATOR_SET = styleable_ANIMATOR_SET;
        final int n4 = 4;
        final int[] array7;
        final int[] styleable_PROPERTY_VALUES_HOLDER = array7 = new int[n4];
        array7[0] = 16843486;
        array7[1] = 16843487;
        array7[2] = 16843488;
        array7[3] = 16843489;
        STYLEABLE_PROPERTY_VALUES_HOLDER = styleable_PROPERTY_VALUES_HOLDER;
        final int[] array8;
        final int[] styleable_KEYFRAME = array8 = new int[n4];
        array8[0] = 16842788;
        array8[1] = 16843073;
        array8[2] = 16843488;
        array8[3] = 16843992;
        STYLEABLE_KEYFRAME = styleable_KEYFRAME;
        final int[] array9;
        final int[] styleable_PROPERTY_ANIMATOR = array9 = new int[n4];
        array9[0] = 16843489;
        array9[1] = 16843781;
        array9[2] = 16843892;
        array9[3] = 16843893;
        STYLEABLE_PROPERTY_ANIMATOR = styleable_PROPERTY_ANIMATOR;
        final int[] array10;
        final int[] styleable_PATH_INTERPOLATOR = array10 = new int[5];
        array10[0] = 16843772;
        array10[1] = 16843773;
        array10[2] = 16843774;
        array10[3] = 16843775;
        array10[4] = 16843781;
        STYLEABLE_PATH_INTERPOLATOR = styleable_PATH_INTERPOLATOR;
    }
}
